language: node_js

sudo: false

cache:
  directories:
    - node_modules

node_js: 9

install:
  - npm install -g yarn
  - yarn install

script:
  - yarn lint

deploy:
  provider: npm
  email: "$NPM_DEPLOY_EMAIL"
  api_key: "$NPM_DEPLOY_TOKEN"
  on:
    branch: master
    tags: true

notifications:
  email:
    on_success: never
    on_failure: change
